### ISSUE TITLE
FileNotFoundError: File b'../data/ted384-metadata.csv' does not exist

### ISSUE THREAD

**Issue by kumar-neelabh** [snap-research/articulated-animation#26]
On running:
`python load_videos.py --metadata ../data/ted384-metadata.csv --format .mp4 --out_folder ../data/TED384-v2 --workers 8 --image_shape 384,384`

I get:

> Traceback (most recent call last):
  File "load_videos.py", line 96, in <module>
    df = pd.read_csv(args.metadata)
  File "/home2/neelabh/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home2/neelabh/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home2/neelabh/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home2/neelabh/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home2/neelabh/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'../data/ted384-metadata.csv' does not exist

**Comment by kumar-neelabh** [comment]
Found it in #12 but please upload it to the repo too

**Comment by johndpope** [comment]
python load_videos.py --metadata ../data/ted384-metadata.csv --format .mp4 --out_folder ../data/TED384-v2 --workers 8 --image_shape 384,384

SHOULD BE
